CREATE TABLE Products(
  ID     INTEGER PRIMARY KEY, 
  description   TEXT NOT NULL,
  amount INTEGER NOT NULL,
  CartId INTEGER NOT NULL,
  CONSTRAINT fk_cart FOREIGN KEY(CartId) REFERENCES Cart(ID) ON DELETE CASCADE
)